from django.urls import path
from.import views
urlpatterns=[
    path('',views.home),
    path('Registration/',views.Registration),
    path('save_registration/',views.save_registration),
    path('check_login/',views.check_login),
    path('user_home/',views.home),
    path('Logout/',views.Logout),
    path('prediction/', views.prediction),
    path('Adminlogin/',views.Adminlogin),
    path('Adminlogincheck/',views.Adminlogincheck),
    path('Adminhomepage/',views.Adminhomepage),
    path("check_prediction/",views.check_prediction),
    path("result/<res>",views.result,name="result"),
    path("users/",views.users),
    path("delete_user/<id>",views.delete_user),
    path('predictions/', views.predictions),
    path("delete_predictions/<id>",views.delete_predictions),
    path("covid_info/",views.covid_info),
    path("news/", views.news),
    path("doctors/", views.doctors),
    path("protect/", views.protect),
    path("about/", views.about),
    path("checkcovid19/", views.checkcovid19),
    path("check_covid/", views.check_covid),
    path("covidchart/", views.covidchart),
    path("doctor_reg/", views.doctor_reg),
    path('save_doctor/', views.save_doctor),
    path('doctor_user/', views.doctor_user),
    path('doctor_check_login/', views.doctor_check_login),
    path('doctor_booking/', views.doctor_booking),
    path('contact_us/', views.contact_us),
    path('doctor_home/', views.doctor_home),
    path('health_dept/', views.health_dept),
    path('health_login/', views.health_login),
    path('Healthlogincheck/', views.Healthlogincheck),
    path('health_notification/', views.health_notification),
    path('search_hospital/<location>', views.search_hospital),
    path('save_booking/', views.save_booking),
    path("track_user/<id>",views.track_user),
    path("save_contactus/", views.save_contactus),
    path("view_contact/", views.view_contact),
    path("delete_contact/<id>", views.delete_contact)

]