# Generated by Django 5.0.3 on 2024-03-06 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_MedicalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('bmi', models.FloatField(null=True)),
                ('hypertensive', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('atrialfibrillation', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('chd', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('diabetes', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('deficiencyanemias', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('depression', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('hyperlipemia', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('renalfailure', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('copd', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('heartrate', models.FloatField(null=True)),
                ('systolicbp', models.FloatField(null=True)),
                ('diastolicbp', models.FloatField(null=True)),
                ('respiratoryrate', models.FloatField(null=True)),
                ('temperature', models.FloatField(null=True)),
                ('spo2', models.FloatField(null=True)),
                ('urineoutput', models.FloatField(null=True)),
                ('hematocrit', models.FloatField(null=True)),
                ('rbc', models.FloatField(null=True)),
                ('mch', models.FloatField(null=True)),
                ('mchc', models.FloatField(null=True)),
                ('mcv', models.FloatField(null=True)),
                ('rdw', models.FloatField(null=True)),
                ('leucocyte', models.FloatField(null=True)),
                ('platelets', models.FloatField(null=True)),
                ('neutrophils', models.FloatField(null=True)),
                ('basophils', models.FloatField(null=True)),
                ('lymphocyte', models.FloatField(null=True)),
                ('pt', models.FloatField(null=True)),
                ('inr', models.FloatField(null=True)),
                ('ntproBNP', models.FloatField(null=True)),
                ('creatinekinase', models.FloatField(null=True)),
                ('creatinine', models.FloatField(null=True)),
                ('ureanitrogen', models.FloatField(null=True)),
                ('glucose', models.FloatField(null=True)),
                ('bloodpotassium', models.FloatField(null=True)),
                ('bloodsodium', models.FloatField(null=True)),
                ('bloodcalcium', models.FloatField(null=True)),
                ('chloride', models.FloatField(null=True)),
                ('aniongap', models.FloatField(null=True)),
                ('magnesiumion', models.FloatField(null=True)),
                ('ph', models.FloatField(null=True)),
                ('bicarbonate', models.FloatField(null=True)),
                ('lacticacid', models.FloatField(null=True)),
                ('pco2', models.FloatField(null=True)),
                ('ef', models.FloatField(null=True)),
                ('result', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='covidapp.registration_tbl')),
            ],
        ),
    ]
