# Generated by Django 5.0.3 on 2024-03-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0004_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='District',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
