# Generated by Django 5.0.3 on 2024-03-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0005_hospital_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='Map',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
