# Generated by Django 5.0.3 on 2024-03-22 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0007_registration_tbl_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Covid19Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breathingProblem', models.CharField(max_length=3, null=True)),
                ('fever', models.CharField(max_length=3, null=True)),
                ('dryCough', models.CharField(max_length=3, null=True)),
                ('soreThroat', models.CharField(max_length=3, null=True)),
                ('runningNose', models.CharField(max_length=3, null=True)),
                ('asthma', models.CharField(max_length=3, null=True)),
                ('chronicLungDisease', models.CharField(max_length=3, null=True)),
                ('headache', models.CharField(max_length=3, null=True)),
                ('heartDisease', models.CharField(max_length=3, null=True)),
                ('diabetes', models.CharField(max_length=3, null=True)),
                ('hyperTension', models.CharField(max_length=3, null=True)),
                ('fatigue', models.CharField(max_length=3, null=True)),
                ('gastrointestinal', models.CharField(max_length=3, null=True)),
                ('abroadTravel', models.CharField(max_length=3, null=True)),
                ('contactWithCovidPatient', models.CharField(max_length=3, null=True)),
                ('attendedLargeGathering', models.CharField(max_length=3, null=True)),
                ('visitedPublicExposedPlaces', models.CharField(max_length=3, null=True)),
                ('familyWorkingInPublicExposedPlaces', models.CharField(max_length=3, null=True)),
                ('wearingMasks', models.CharField(max_length=3, null=True)),
                ('sanitizationFromMarket', models.CharField(max_length=3, null=True)),
                ('result', models.CharField(max_length=20, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='covidapp.registration_tbl')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_DoctorBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('date', models.DateField(max_length=100, null=True)),
                ('time', models.TimeField(max_length=100, null=True)),
                ('area', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('post_code', models.CharField(max_length=100, null=True)),
                ('Doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='covidapp.doctorregistration')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='covidapp.registration_tbl')),
            ],
        ),
    ]
