# Generated by Django 5.0.3 on 2024-03-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0008_tbl_covid19prediction_tbl_doctorbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration_tbl',
            name='mobile',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
