# Generated by Django 5.0.3 on 2024-03-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0010_contactus_tbl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus_tbl',
            name='created_at',
        ),
        migrations.AddField(
            model_name='contactus_tbl',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
