# Generated by Django 5.0.3 on 2024-03-25 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0011_remove_contactus_tbl_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus_tbl',
            name='message',
        ),
    ]
